### PR TITLE
added the state attribute as per the issue #149

### PR DESCRIPTION
**Pull request by shubhvashisht**

### CODE REVIEW

**Comment by seratch** [comment]
Oh, I also worked on it. Do you have specific reasons for skipping notify_on_cancel?

**Comment by seratch** [comment]
FYI: my pull request #151

**Comment by shubhvashisht** [comment]
no, I just didnt have the use for it currently and was wanting to have the state to work sooner than later.

**Comment by seratch** [comment]
I got it. Let me merge #151 and close this one without merging this. Thank you for submitting a pull request.

**Pull request closed without merging**
