### PR TITLE
Enable to access raw response in MethodsClient

### PR DESCRIPTION
**Pull request by seratch**
This pull request brings the changes which enable library users to access raw okhttp3 response objects. ref #126 cc @namedgraph

### CODE REVIEW

**Comment by namedgraph** [comment]
It addresses the immediate need.

But I would suggest a broader refactoring. `MethodsClientImpl` is a bad design pattern - it's basically a mapping collection which suggests the logic is misplaced. It should be a generic class that does not know about parameters. Try to move parameters into the `Request` classes and make them extend `Builder`:

    public class ConversationsHistoryRequest extends FormBody.Builder implements SlackApiRequest {

        private final Form.Builder builder;

        private ConversationsHistoryRequest() {
            builder = new Builder();
        }

        public ConversationsHistoryRequest new() {
            return new ConversationsHistoryRequest();
        }
        
        public ConversationsHistoryRequest channel(String channel) {
            if (token != null) builder.add("channel", channel);
            else builder.remove("channel");
            return this;
        }

        public ConversationsHistoryRequest token(String token) {
            if (token != null) builder.add("token", token);
            else builder.remove("token");
            return this;
        }

        ...

    }

Then `MethodsClientImpl` will need only few generic methods:

    public class MethodsClientImpl implements MethodsClient {

            protected <T> T doPostForm( ...

            protected <T> T doPostFormWithToken(...

            protected <T> T doPostMultipart(...

    }

And the invocation looks simply like this:

    ConversationsHistoryRequest req = ConversationsHistoryRequest.new().
        channel("C1234567890").
        token("xxxx-xxxxxxxxx-xxxx");
    MethodsClient client = new MethodsClientImpl();
    client.doPostForm(req, ...);

**Comment by seratch** [comment]
I understand your point but I'm not willing to inherit `FormBody.Builder`. To me, having both setters and `add(key, value)` method as public APIs is not clean.

**Comment by namedgraph** [comment]
That is the nature of a builder.

My point is that `MethodsClientImpl ` is a bottleneck in your codebase which prevents it from being more generic/functional.

It's your project, do as you wish :)

**Comment by seratch** [comment]
Thank you for your feedback and also understanding. I’m going to ship a new version including this change this weekend.

**Pull request merged**
