### PR TITLE
Add full support for `cursor` based pagination

### PR DESCRIPTION
**Pull request by joeltoby**
The [_'Methods supporting cursor-based pagination'_ section of the Slack API documentation](https://api.slack.com/docs/pagination#methods_supporting_cursor-based_pagination) lists all API methods that support _cursor based_ pagination.  These are currently:

- channels.list
- conversations.history
- conversations.list
- conversations.members
- conversations.replies
- im.list
- users.list

This PR brings JSlack's support for cursor pagination fully up-to-date by adding `ResponseMetadata` to API response models that should support it but don't already have it.  I.E:

- `ChannelsListResponse`
- `ConversationsHistoryResponse`
- `ImListResponse`
- `UsersListResponse`

### CODE REVIEW

**Comment by seratch** [comment]
Thanks. Could you add some test code which makes sure the existence of the field?

**Comment by joeltoby** [comment]
So it turns out that the field is only included in the response if there are more pages (i.e. hasMore = true).  Therefore, I have updated some of the tests to ensure that there are more pages (i.e. setting a low limit for the items per page).

The tests are done now.

**Comment by seratch** [comment]
Thanks, LGTM.

**Comment by joeltoby** [comment]
Thank you

**Pull request merged**
