### PR TITLE
Improve SlackEventsApiServlet.java to verify X-Slack-Signature header (fixes #163 )

### LINKED ISSUE #163: Question: How do you verify the payload coming from EventsAPI?
Congratulations for the API it's very feature complete. I got one doubt on origin verification. You know you can verify requests on slack according to their practices: https://api.slack.com/docs/verifying-requests-from-slack

Maybe I just missed some part of the code but does the code for EventsAPI get the request headers and do that validation? Before calling the handlers?

Thanks!

### PR DESCRIPTION
**Pull request by shubhvashisht**
fixed the test case.

### CODE REVIEW

**Comment by seratch** [comment]
Thank you for making a pull request for this issue. Your change seems to be:
* This one doesn't verify `X-Slack-Signature` header yet (hint: SlackSignatureVerifier)
* I would like to avoid having unrelated changes like creating a Map object containing all request headers
* Some related tests are failing - check the CI build results
* Please apply code formatter (ideally, IntelliJ IDEA's default one) after pushing your code

**Comment by seratch** [comment]
Thank you for making a pull request for this issue. Let me suggest:
* This one doesn't verify `X-Slack-Signature` header yet (hint: SlackSignatureVerifier)
* I would like to avoid having unrelated changes like creating a Map object containing all request headers
* Some related tests are failing - check the CI build results
* Please apply code formatter (ideally, IntelliJ IDEA's default one) before pushing your code

**Comment by seratch** [comment]
ref #163

**Comment by shubhvashisht** [comment]
> This one doesn't verify X-Slack-Signature header yet (hint: SlackSignatureVerifier)

Yeah, for now it is not doing slack signature verify. I was thinking that probably client can implement it and then call this function. But as I think more, I think an optional parameter will be helpful for anyone who wants to use this feature with signed secret. I will work on it.

> I would like to avoid having unrelated changes like creating a Map object containing all request headers

Yes, i realized that and have removed the same.

> Some related tests are failing - check the CI build results
Already fixed.

**Comment by seratch** [comment]
>I think an optional parameter will be helpful for anyone who wants to use this feature with signed secret.

Good point. 1) having a constructor which requires signing secret or 2) defining a getter `String getSlackSignedSecret()` may be reasonable. I prefer going with 1)

**Comment by shubhvashisht** [comment]
closing the pull request as added new features.

**Pull request closed without merging**
