### PR TITLE
Added a new payload and handler for app_home_open

### PR DESCRIPTION
**Pull request by d-subrahmanyam**
Added a new payload and handler for app_home_open

### CODE REVIEW

**Comment by d-subrahmanyam** [comment]
When I was trying to create and use this class locally, I was getting a ClassCastException.

**Comment by seratch** [comment]
@d-subrahmanyam Good catch. Thank you for making a PR! I'm going to release a new version including this fix today.

> When I was trying to create and use this class locally, I was getting a ClassCastException.

If you still have the error message / stacktrace, could you share it with us just for reference?

**Comment by seratch** [comment]
I just shipped a new version 1.8.1. Thanks again 👍

**Comment by d-subrahmanyam** [comment]
Sure. Thanks.

**Pull request merged**
