### PR TITLE
Fix #184: Attachment blocks result in invalid_attachments response

### LINKED ISSUE #184: Attachment blocks result in invalid_attachments response
Attachment blocks (#157) don't work as the JSONified `Attachment` includes booleans: `"is_msg_unfurl":false,"is_reply_unfurl":false,"is_thread_root_unfurl":false,"is_app_unfurl":false` which cause Slack to give an `invalid_attachments` response.

Probably needs a solution similar to #70

### PR DESCRIPTION
**Pull request by domdomegg**
Basically copied the fix in #71

### CODE REVIEW

**Comment by seratch** [comment]
Thanks! LGTM

**Comment by domdomegg** [comment]
Any chance we could release a new version with this fix soon (not crazy urgent, but by sometime next week)? Currently using jSlack in a project and this is blocking me from finishing it off. Thanks for the amazing library 🥇

**Comment by seratch** [comment]
Will release very soon.  Thank you for using this library!

**Comment by seratch** [comment]
FYI: jSlack version 1.7.5 including your changes is available on Maven central.

**Pull request merged**
