### PR TITLE
Add SlackApiRequest marker interface

### PR DESCRIPTION
**Pull request by joeltoby**
All request objects now implement SlackApiRequest.  As per issue #7

### CODE REVIEW

**Comment by seratch** [comment]
How about SlackApiResponse as well?

**Comment by seratch** [comment]
It would be appreciated if you specify your GitHub email address (`git config user.email {your GitHub email address}`) before pushing commits. If your commits are related to valid email address, I'll be able to list you [here](https://github.com/seratch/jslack/graphs/contributors).

**Comment by joeltoby** [comment]
Apologies re the email - I thought it was set globally on my machine.

RE: SlackApiResponse - Somebody beat me to it.  It's already done:  [SlackApiResponse.java](https://github.com/seratch/jslack/blob/master/src/main/java/com/github/seratch/jslack/api/methods/SlackApiResponse.java)

**Comment by joeltoby** [comment]
I've added the email.  Thanks for adding me.

**Pull request merged**
